# See the documentation for more information:
# https://packit.dev/docs/configuration/

specfile_path: cswrap.spec

# add or remove files that should be synced
files_to_sync:
    - cswrap.spec
    - .packit.yaml

# name in upstream package repository or registry (e.g. in PyPI)
upstream_package_name: cswrap
# downstream (Fedora) RPM package name
downstream_package_name: cswrap

actions:
    post-upstream-clone: ./make-srpm.sh --generate-spec

jobs:
    - &copr
      job: copr_build
      trigger: commit
      metadata:
        targets:
            - epel-all-aarch64
            - epel-all-x86_64
            - fedora-all-aarch64
            - fedora-all-x86_64
        branch: main  # only used for commit trigger

    - <<: *copr
      trigger: pull_request
