language: c
compiler: gcc
dist: trusty

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq apt-transport-https
    - echo "deb https://kdudka.fedorapeople.org/csbuild trusty contrib" | sudo tee -a /etc/apt/sources.list
    - sudo apt-get update -qq

install:
    - sudo apt-get install cmake3 valgrind
    - sudo apt-get install -y --force-yes csbuild

script:
    - make -j9 distcheck CTEST='ctest -j9'
    - test -z "$TRAVIS_COMMIT_RANGE" || csbuild --git-commit-range "$TRAVIS_COMMIT_RANGE" -c "make distclean && make -j9" --git-bisect --print-fixed

env:
    global:
        # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
        #   via the "travis encrypt" command using the project repo's public key
        - secure: "fzUgw3blklk1zNQOlW6GKXM4XpFll0/4OxutoqE0sMtRX90oAHUjRJdWfJzDub+zVnoXp5lpieX2KCiPnayrknhwYHmcSTVxsIhuWTAhaGsxzVEUZHDcqwjSB3LiuiO2/XjtI6O4SwootfxUha2B4qDeqXDXqDxu1C3mQ/efR70="

addons:
    coverity_scan:
        project:
            name: "kdudka/cswrap"
            description: "Generic Compiler Wrapper"
        notification_email: kdudka@redhat.com
        build_command_prepend: make distclean
        build_command: make -j9
        branch_pattern: master
