---
on: [push, pull_request]

jobs:
  ubuntu:
    name: Ubuntu ${{ maxtrix.version }}
    strategy:
      fail-fast: false
      matrix:
        version: [18.04, 20.04]

    runs-on: ${{ matrix.version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt-get install cmake valgrind

      - name: Build and check
        run: make distcheck

  coverity:
    name: Coverity Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Coverity scan
        uses: vapier/coverity-scan-action@v1
        with:
          email: ${{ secrets.COVERITY_SCAN_EMAIL }}
          token: ${{ secrets.COVERITY_SCAN_TOKEN }}
          project: csutils/cswrap
          command: make
